### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by ghost** [SkyHeroes/CSMC#3]
Checking event.getView().getTitle() to see whether your custom inventory is being used is unsafe, as renaming a chest in an anvil allows users to set their own inventory titles. The correct way to check if your custom inventory is involved with an event is by using custom holders, see here: https://docs.papermc.io/paper/dev/custom-inventory-holder

**Comment by ricsal1** [comment]
Sorry for the late response. We will look into it
